language: python

python:
    - "2.7"

install:
    - deactivate
    - source devtools/ci/install_conda.sh
    - export PYTHONUNBUFFERED=true

script:
    - conda install --yes conda-build
    # when OPS conda doesn't work, use the next 2 lines
    - source devtools/no-ops-conda/make_build.sh
    - source devtools/no-ops-conda/build.sh
    # when OPS conda works, use the line below
    #- conda build devtools/conda-recipe
    # other packages are built in the build.sh
    
    - source activate _test
    - nosetests -v --with-coverage

after_success:
    - coveralls

env:
    matrix:
        - python=2.7 CONDA_PY=27 CONDA_NPY=110
