language: python

python:
    - "2.7"

install:
    - deactivate
    - source devtools/ci/install_conda.sh
    - export PYTHONUNBUFFERED=true

script:
    - conda install --yes conda-build
    # other packaged are built in the build.sh
    - conda build devtools/conda-recipe
    
    - source activate _test
    - nosetests -v --with-coverage

after_success:
    - coveralls

env:
    matrix:
        - python=2.7 CONDA_PY=27 CONDA_NPY=110
