language: python

python:
    - "2.7"

install:
    - deactivate
    - source devtools/ci/install_conda.sh
    - export PYTHONUNBUFFERED=true

script:
    # when OPS conda doesn't work, use the next lines
    #- conda install --yes conda-build
    #- conda config --set always_yes true
    #- source devtools/no-ops-conda/make_build.sh
    #- source devtools/no-ops-conda/build.sh
    # when OPS conda works, use the line below
    - conda install --yes --name test --use-local dynamiq_samplers-dev
    - source activate test
    - conda install --yes openpathsampling
    - conda install --yes nose python-coveralls

    # other packages are built in the build.sh
    - nosetests -v --with-coverage

after_success:
    - coveralls

env:
    matrix:
        - python=2.7 CONDA_PY=27 CONDA_NPY=110
